# Generated by Django 5.2.8 on 2025-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
